import { compileFromFile } from 'json-schema-to-typescript';
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';

async function generate() {
  const schemaPath = join(import.meta.dirname, '../protocol/schema.json');
  const outputPath = join(import.meta.dirname, '../types/protocol.d.ts');

  console.log(`Generating types from ${schemaPath}...`);

  try {
    const ts = await compileFromFile(schemaPath, {
      bannerComment: '/* eslint-disable */\n/**\n * This file was automatically generated by json-schema-to-typescript.\n * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n * and run the generation script to regenerate this file.\n */',
      additionalProperties: false
    });

    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, ts);

    console.log(`Successfully generated types to ${outputPath}`);
  } catch (error) {
    console.error('Failed to generate types:', error);
    process.exit(1);
  }
}

generate();
