/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the generation script to regenerate this file.
 */

/**
 * Unified communication protocol between tenvy-server and tenvy-client.
 */
export interface TenvyProtocol {
  agentMetadata?: AgentMetadata;
  command?: Command;
  commandResult?: CommandResult;
  agentRegistrationRequest?: AgentRegistrationRequest;
  agentSyncRequest?: AgentSyncRequest;
  pingCommandPayload?: PingCommandPayload;
  shellCommandPayload?: ShellCommandPayload;
  agentControlCommandPayload?: AgentControlCommandPayload;
}
export interface AgentMetadata {
  hostname: string;
  username: string;
  os: string;
  architecture: string;
  ipAddress?: string;
  publicIpAddress?: string;
  tags?: string[];
  version?: string;
  hardwareId?: string;
}
export interface Command {
  id: string;
  name: string;
  payload: {};
  createdAt: string;
  signature?: string;
}
export interface CommandResult {
  commandId: string;
  success: boolean;
  output?: string;
  error?: string;
  completedAt: string;
}
export interface AgentRegistrationRequest {
  token?: string;
  metadata: AgentMetadata;
}
export interface AgentSyncRequest {
  status: "online" | "offline" | "busy";
  timestamp: string;
  metrics?: {
    memoryBytes?: number;
    goroutines?: number;
    uptimeSeconds?: number;
  };
  results?: CommandResult[];
}
export interface PingCommandPayload {
  message?: string;
}
export interface ShellCommandPayload {
  command: string;
  timeoutSeconds?: number;
  workingDirectory?: string;
  elevated?: boolean;
  environment?: {
    [k: string]: string;
  };
}
export interface AgentControlCommandPayload {
  action: "disconnect" | "reconnect" | "shutdown" | "restart" | "sleep" | "logoff";
  reason?: string;
  force?: boolean;
}
